### ISSUE TITLE
OpenJS Foundation Bootstrap Team Meeting 2019-03-18

### ISSUE THREAD

**Issue by MylesBorins** [openjs-foundation/bootstrap#120]
## Time

**UTC Mon 18-Mar-2019 13:00 (01:00 PM)**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Mon 18-Mar-2019 06:00 (06:00 AM) |
| US / Mountain | Mon 18-Mar-2019 07:00 (07:00 AM) |
| US / Central  | Mon 18-Mar-2019 08:00 (08:00 AM) |
| US / Eastern  | Mon 18-Mar-2019 09:00 (09:00 AM) |
| London        | Mon 18-Mar-2019 13:00 (01:00 PM) |
| Amsterdam     | Mon 18-Mar-2019 14:00 (02:00 PM) |
| Moscow        | Mon 18-Mar-2019 16:00 (04:00 PM) |
| Chennai       | Mon 18-Mar-2019 18:30 (06:30 PM) |
| Hangzhou      | Mon 18-Mar-2019 21:00 (09:00 PM) |
| Tokyo         | Mon 18-Mar-2019 22:00 (10:00 PM) |
| Sydney        | Tue 19-Mar-2019 00:00 (12:00 AM) |

Or in your local time:
* http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Bootstrap%20Team+Meeting+2019-03-18&iso=20190318T13
* or http://www.wolframalpha.com/input/?i=01PM+UTC%2C+Mar+18%2C+2019+in+local+time

## Links

* **Minutes Google Doc**: <https://docs.google.com/document/d/1UpJlOTlON6B587ge1SpOIqUMObGXO_BcPPgez6bHpzE/edit?usp=sharing>
* _Previous Minutes Google Doc: <https://docs.google.com/document/d/1l7hoJXaXaqFKRoLOEgPfXJuxTnGp9GoOpwz0qDhXVBs/edit>_

## Agenda

Extracted from **bootstrap-agenda** labelled issues and pull requests from the **nodejs org** prior to the meeting.

### nodejs/bootstrap

* doc: add responsibility for charter review [#116](https://github.com/nodejs/bootstrap/pull/116)
* proposal: move expectations to stage 3 [#108](https://github.com/nodejs/bootstrap/pull/108)
* Project Directed Funding [#90](https://github.com/nodejs/bootstrap/issues/90)
* Steps to bootstrap CPC and new Foundation [#115](https://github.com/nodejs/bootstrap/issues/115)

## Invited

* Node.js Members: @nodejs/members
* JSF Project Maintainers
* JSF TAC
* Node.js Foundation Board of Directors
* JSF Board of Directors

## Notes

The agenda comes from issues labelled with `bootstrap-agenda` across **all of the repositories in the nodejs org**. Please label any additional issues that should be on the agenda before the meeting starts.

## Joining the meeting

* link for participants: https://zoom.us/j/779273015
* For those who just want to watch: https://www.youtube.com/c/nodejs+foundation/live

**Comment by MylesBorins** [comment]
updated to account for DST

**Comment by mcollina** [comment]
Unfortunately I will not be able to join :/.

**Comment by mhdawson** [comment]
PR for minutes: https://github.com/openjs-foundation/bootstrap/pull/122

**Comment by SMotaal** [comment]
@MylesBorins Maybe it's just me, but I inferred from the emails that the new times are accounting for DST and scrolled down aiming to be here per the times listed.

I am not sure if GitHub is looking to make changes to issue emails when the issue itself changes which would the ideal way to overcome this scenario.

Meanwhile, if this is confusing to others, would it be a good idea to include the updated times in that comment so that people can see it in the follow up email?

Thanks and sorry for not making it — this meeting always catches me on Mondays and yet somehow making a mental note to pay closer attention to not confuse times is always an afterthought 😉

**Comment by inidaname** [comment]
@SMotaal +1 your comments, as per time received in mail.

Thank you, sorry for not making it.

**Comment by MylesBorins** [comment]
Apologies for the confusion, will include new times in follow up email if
we need to correct in the future

**Comment by mhdawson** [comment]
Going to close this since meeting help and PR for meeting opened.
