### ISSUE TITLE
More Volunteers for Chairing Meetings

### ISSUE THREAD

**Issue by MylesBorins** [openjs-foundation/bootstrap#123]
Up until this point I have been chairing the meetings... I kind of took this on and it has been easy for me to keep doing it. Now that we have the new foundation launched I think it might be nice if more folks could step up and help with this.

Any volunteers?

**Comment by codeekage** [comment]
I’d really love to step up and get more involved. 😅

**Comment by codeekage** [comment]
I have a little issue with the current meeting time. 😅

**Comment by jorydotcom** [comment]
Happy to help chair, @MylesBorins

**Comment by mhdawson** [comment]
I'm happy to help chair as well.

**Comment by yosuke-furukawa** [comment]
I am also happy to help chair @MylesBorins .

**Comment by MylesBorins** [comment]
This has been going well yay
