### ISSUE TITLE
Infrastructure: Mailing lists

### ISSUE THREAD

**Issue by brianwarner** [openjs-foundation/bootstrap#134]
I'm taking care of some administrative tasks, like setting up the mailing lists on the "@lists.openjsf.org" subdomain.  I'm looking for input on what lists we will need to support the various governance structures, and how they should be configured.

I'm assuming that the CPC will use GitHub for most things.  However, there may be certain scenarios where a team requires a private channel.  For example, moderation discussions.

This is an open call for input on what lists I should create, and how they should be configured.  Please propose lists as comments to this issue, and please provide this information:

- Which group will use it?
- Should it be listed on https://lists.openjsf.org?
- Is self-subscription allowed?
- Are the archives public, or for members only?
- Can non-members email the list (e.g. to file reports)?
- Can members email the list, or is it announce-only?

We can discuss these further in the bootstrap calls.

**Comment by mhdawson** [comment]
From https://github.com/openjs-foundation/bootstrap/blob/master/proposals/stage-1/CODE_OF_CONDUCT/FOUNDATION_CODE_OF_CONDUCT_REQUIREMENTS.md we’d need coc-escalation@xxx.org and report@xxxx.org

**Comment by mhdawson** [comment]
Maybe start with 

* cpc-private
* report
* coc-escalation

**Comment by joesepi** [comment]
@brianwarner these are from the last meeting notes. Can you confirm and add any updates if there are any? Part of why I ask is because `coc-escalation@` is referenced in #147. Thanks!

> * Infrastructure: Mailing lists [#134](https://github.com/openjs-foundation/bootstrap/issues/134)
>   * Brian having been working on getting pieces in place
>   * Current lists:
>     * announce@ 
>     * report@
>     * coc-escalation@
>     * projects@
>     * cpc-private@  
>   * Also created announcement list for key interested parties in the project. Once get list
>      of current people that she is emailing.
>

**Comment by brianwarner** [comment]
@joesepi Yep! Confirmed, that's what I have so far. 

I'll comment in #147, but it's important to note that the lists are on the "@lists.openjsf.org" subdomain.  I should have spelled that out in the minutes.
