### ISSUE TITLE
OpenJS Foundation Bootstrap Team Meeting 2019-04-01

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/bootstrap#136]
## Time

**UTC Mon 01-Apr-2019 13:00 (01:00 PM)**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Mon 01-Apr-2019 06:00 (06:00 AM) |
| US / Mountain | Mon 01-Apr-2019 07:00 (07:00 AM) |
| US / Central  | Mon 01-Apr-2019 08:00 (08:00 AM) |
| US / Eastern  | Mon 01-Apr-2019 09:00 (09:00 AM) |
| London        | Mon 01-Apr-2019 14:00 (02:00 PM) |
| Amsterdam     | Mon 01-Apr-2019 15:00 (03:00 PM) |
| Moscow        | Mon 01-Apr-2019 16:00 (04:00 PM) |
| Chennai       | Mon 01-Apr-2019 18:30 (06:30 PM) |
| Hangzhou      | Mon 01-Apr-2019 21:00 (09:00 PM) |
| Tokyo         | Mon 01-Apr-2019 22:00 (10:00 PM) |
| Sydney        | Tue 02-Apr-2019 00:00 (12:00 AM) |

Or in your local time:
* http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Bootstrap%20Team+Meeting+2019-04-01&iso=20190401T13
* or http://www.wolframalpha.com/input/?i=01PM+UTC%2C+Apr+01%2C+2019+in+local+time

## Links

* **Minutes Google Doc**: <https://docs.google.com/document/d/1YrP5yILvnCedkxQvIzol6yhBI4znbbDNE0mfDC-VbyA/edit?usp=sharing>
* _Previous Minutes Google Doc: <https://docs.google.com/document/d/1meg7_RkWWpEEKzK_KmP3hK9D25bavrehdViVeB0B8a8/edit>_

## Agenda

Extracted from **bootstrap-agenda** labelled issues and pull requests from the **openjs-foundation org** prior to the meeting.

### openjs-foundation/bootstrap

* Infrastructure: Mailing lists [#134](https://github.com/openjs-foundation/bootstrap/issues/134)
* add PROJECT.md file [#132](https://github.com/openjs-foundation/bootstrap/pull/132)
* Create process for new projects joining foundation [#130](https://github.com/openjs-foundation/bootstrap/issues/130)
* Review meeting times [#129](https://github.com/openjs-foundation/bootstrap/issues/129)
* Project Housekeeping: Create Checklist for New Projects / Updating Existing Projects [#121](https://github.com/openjs-foundation/bootstrap/issues/121)
* Steps to bootstrap CPC and new Foundation [#115](https://github.com/openjs-foundation/bootstrap/issues/115)

## Invited

* OpenJS Foundation Project Maintainers
* OpenJS Foundation Board of Directors

## Notes

The agenda comes from issues labelled with `bootstrap-agenda` across **all of the repositories in the openjs-foundation org**. Please label any additional issues that should be on the agenda before the meeting starts.

## Joining the meeting

* link for participants: https://zoom.us/j/779273015
* For those who just want to watch: https://www.youtube.com/c/nodejs+foundation/live

**Comment by mhdawson** [comment]
PR for minutes: closing; https://github.com/openjs-foundation/bootstrap/pull/139
