### ISSUE TITLE
Code of Conduct email aliases

### ISSUE THREAD

**Issue by brianwarner** [openjs-foundation/bootstrap#141]
@mhdawson - I notice the CoC proposal has two different reporting paths, with separate emails (report@ and coc-escalation@).  

While there are no technical issues with having two lists, would it be clearer to have one destination for filing reports?  Is there a historical reason for having two paths?

**Comment by hackygolucky** [comment]
@brianwarner Those are two different groups. report@ is general moderation team reporting mechanism if people aren't comfortable reporting on GitHub. coc-escalation@ is when there's a particularly tough problem that may involve core maintainers/leadership and is a smaller, specifically identified group trusted to deal with escalation situations(means it may require Board involvement and the ED)

**Comment by brianwarner** [comment]
Thanks @hackygolucky!  That helps.
