### ISSUE TITLE
Create Team for CPC voting reps?

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/bootstrap#163]
I think it would be a good idea to create a CPC voting reps team under the OpenJS Foundation. WDYT?

**Comment by MylesBorins** [comment]
+1... I'm assuming it would be a child team of a general CPC team.

CPC-Voting?
CPC-Voting-Members?

**Comment by mhdawson** [comment]
+1

**Comment by MylesBorins** [comment]
I've created a cpc team and a child-team cpc-voting members.

I've added the members that are representing impact project and we can the remaining members once we lock down who they are.
